/**
 * MongoDB Feedback System Types
 *
 * Defines the complete schema for feedback documents stored in MongoDB.
 * This provides rich metadata for traceability and context preservation.
 */

/**
 * Feedback type categories for the F1 module questions
 */
export type F1FeedbackType =
  | 'positioning'
  | 'brand-tone'
  | 'lead-strategy'
  | 'general'
  | 'custom'

/**
 * Answer option structure - stores the available choices for a question
 */
export interface AnswerOption {
  id: string
  label: string
  description?: string
}

/**
 * Slide content metadata - captures the context of the question
 */
export interface SlideContentMetadata {
  /** Title of the slide/question */
  title: string
  /** The question prompt shown to the user */
  questionPrompt: string
  /** Question number in the flow (e.g., 1 of 3) */
  questionNumber?: number
  /** Total number of questions in the flow */
  totalQuestions?: number
  /** Available answer options for this question */
  answerOptions: AnswerOption[]
}

/**
 * User response structure - captures what the user selected
 */
export interface UserResponse {
  /** The ID of the selected option (null if no selection) */
  selectedOptionId: string | null
  /** The display label of the selected option */
  selectedOptionLabel: string | null
  /** Custom text for "other" selections */
  customText?: string
  /** Additional free-text feedback */
  additionalFeedback?: string
}

/**
 * Complete MongoDB feedback document structure
 *
 * This is the full document stored in the `feedback_test` collection.
 */
export interface MongoFeedbackDocument {
  /** MongoDB document ID (optional on client, generated by server) */
  _id?: string

  // Source identification
  /** Unique identifier for the presentation */
  presentationId: string
  /** Module identifier (e.g., "f1", "m1") */
  moduleId: string
  /** Slide identifier (e.g., "f1-02-positioning-question") */
  slideId: string
  /** Unique form identifier for grouping multi-slide flows */
  formId: string
  /** Session identifier for tracking individual review sessions */
  sessionId: string

  // Slide content metadata (for traceability)
  /** Complete slide content for context preservation */
  slideContent: SlideContentMetadata

  // User response
  /** The user's response to this question */
  userResponse: UserResponse

  // Reviewer info (optional)
  /** Reviewer's name */
  reviewerName?: string
  /** Reviewer's email */
  reviewerEmail?: string

  // Categorization
  /** Type of feedback question */
  feedbackType: F1FeedbackType

  // Timestamps
  /** When the feedback was created */
  createdAt: Date | string
  /** When the feedback was last updated */
  updatedAt: Date | string
}

/**
 * Data structure for submitting feedback to MongoDB
 *
 * This is what the client sends to the API endpoint.
 * Timestamps are added server-side.
 */
export interface MongoFeedbackSubmission {
  // Source identification
  presentationId: string
  moduleId: string
  slideId: string
  formId: string
  sessionId: string

  // Slide content metadata
  slideContent: SlideContentMetadata

  // User response
  userResponse: UserResponse

  // Reviewer info (optional)
  reviewerName?: string
  reviewerEmail?: string

  // Categorization
  feedbackType: F1FeedbackType
}

/**
 * Batch submission for multi-question feedback flows
 *
 * Used when submitting all answers from a multi-slide form at once.
 */
export interface MongoFeedbackBatchSubmission {
  /** Common metadata for all submissions in the batch */
  common: {
    presentationId: string
    moduleId: string
    formId: string
    sessionId: string
    reviewerName?: string
    reviewerEmail?: string
  }
  /** Individual question submissions */
  questions: Array<{
    slideId: string
    slideContent: SlideContentMetadata
    userResponse: UserResponse
    feedbackType: F1FeedbackType
  }>
  /** Additional feedback text from summary slide */
  additionalFeedback?: string
}

/**
 * Query filters for retrieving feedback from MongoDB
 */
export interface FeedbackQueryFilters {
  /** Filter by presentation ID */
  presentationId?: string
  /** Filter by module ID */
  moduleId?: string
  /** Filter by slide ID */
  slideId?: string
  /** Filter by form ID */
  formId?: string
  /** Filter by session ID */
  sessionId?: string
  /** Filter by feedback type */
  feedbackType?: F1FeedbackType
  /** Date range filter - start */
  startDate?: Date | string
  /** Date range filter - end */
  endDate?: Date | string
  /** Pagination - number of results */
  limit?: number
  /** Pagination - skip results */
  offset?: number
}

/**
 * Aggregation options for analytics queries
 */
export interface FeedbackAggregationOptions {
  /** Group by field */
  groupBy?: 'presentationId' | 'moduleId' | 'slideId' | 'formId' | 'feedbackType'
  /** Include counts */
  includeCounts?: boolean
  /** Include option distribution */
  includeOptionDistribution?: boolean
}

/**
 * Response from MongoDB feedback API
 */
export interface MongoFeedbackResponse {
  success: boolean
  /** Document ID on successful insert */
  documentId?: string
  /** Error message on failure */
  error?: string
}

/**
 * Response for batch submission
 */
export interface MongoFeedbackBatchResponse {
  success: boolean
  /** Number of documents inserted */
  insertedCount?: number
  /** Array of inserted document IDs */
  documentIds?: string[]
  /** Error message on failure */
  error?: string
}

/**
 * Response for feedback retrieval
 */
export interface MongoFeedbackRetrievalResponse {
  success: boolean
  /** Retrieved feedback documents */
  data?: MongoFeedbackDocument[]
  /** Total count (for pagination) */
  totalCount?: number
  /** Error message on failure */
  error?: string
}
